// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "MetaData": {
    "Root": {
      "title": "Ozone",
      "description": "A specialized store for dental, pharmacy, and medical tools with reliable maintenance services."
    }
  },
  "LandingPage": {
    "hello": "hello"
  }
};
export default messages;